Make 0006_emailaddress_lower reversible
- Migrations cannot be reversed because the operation is not defined
- Set backwards as a no-op

Fixes:
```
django.db.migrations.exceptions.IrreversibleError: Operation <RunPython <function forwards at 0x7f3922aca660>> in account.0006_emailaddress_lower is not reversible
```